{% set name = "cads-api-client" %}
{% set version = "1.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 9551c41d3ba8c73f8789b8c1e280da630805e807401424250127043f91538c68

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools >=64
    - setuptools-scm >=8
    - pip
  run:
    - python >=3.7
    - attrs
    - multiurl
    - requests
    - typing-extensions

test:
  imports:
    - cads_api_client
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ecmwf-projects/cads-api-client
  summary: CADS API Python client
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - akrherz
    - ocefpaf
