{% set name = "cads-api-client" %}
{% set version = "1.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 7d5197deec73e5d2c471fca46530f1b791e544b4b35408b4bbc6ccd821ca899a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=64
    - setuptools-scm >=8
    - pip
  run:
    - typing_extensions
    - python >=3.8
    - attrs
    # For python3.13 support
    - multiurl >=0.3.2
    - requests
    - typing-extensions

test:
  imports:
    - cads_api_client
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ecmwf-projects/cads-api-client
  summary: CADS API Python client
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - akrherz
    - ocefpaf
