{% set name = "cads-api-client" %}
{% set version = "1.5.4" %}
{% set python_min = python_min|default("3.8") %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: f06a405eac585131cb140180cbc2bf9c2784b3dbd6278411d3e9f53d78b7f933

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}.*
    - setuptools >=64
    - setuptools-scm >=8
    - pip
  run:
    - typing_extensions
    - python >={{ python_min }}
    - attrs
    # For python3.13 support
    - multiurl >=0.3.2
    - requests
    - typing-extensions

test:
  imports:
    - cads_api_client
  commands:
    - pip check
  requires:
    - python ={{ python_min }}
    - pip

about:
  home: https://github.com/ecmwf-projects/cads-api-client
  summary: CADS API Python client
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - akrherz
    - ocefpaf
