{% set name = "cads-api-client" %}
{% set version = "1.4.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: cf6029d3320e04032575f39d681cbdce8f1e12cba15de07f9e8ecae676cde5b0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    # awaiting multiurl release, remove legacy-cgi once done
    - python >=3.7,<3.13
    - legacy-cgi
    - setuptools >=64
    - setuptools-scm >=8
    - pip
  run:
    - typing_extensions
    - python >=3.7,<3.13
    - attrs
    - multiurl
    - requests
    - typing-extensions

test:
  imports:
    - cads_api_client
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ecmwf-projects/cads-api-client
  summary: CADS API Python client
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - akrherz
    - ocefpaf
