{% set name = "cads-api-client" %}
{% set version = "0.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cads-api-client-{{ version }}.tar.gz
  sha256: 62c9f20da0ba7cb20803b91e6689f0ee89bd36dafce44ebb3c897a04ff164ffb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools >=45
    - setuptools-scm >=6.2
    - pip
  run:
    - python >=3.7
    - attrs
    - multiurl
    - requests
    - typing-extensions

test:
  imports:
    - cads_api_client
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ecmwf-projects/cads-api-client
  summary: CADS API Python client
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
